### ISSUE TITLE
[ERROR] Error: docusaurus_tag meta tag not found

### ISSUE THREAD

**Issue by spham** [cmfcmf/docusaurus-search-local#102]
### Please describe the bug you are seeing

[ERROR] Unable to build website for locale en.
[ERROR] Error: docusaurus_tag meta tag not found. This is a bug and should never happen.

### How can we best reproduce the bug?

    npx create-docusaurus@latest testdoc classic

add this follow

```
 plugins: [
    [
      require.resolve("@cmfcmf/docusaurus-search-local"),
      {
        language: "fr",
      }
    ],
  ],
```

npm run build

### Which version of Docusaurus and @cmfcmf/docusaurus-search-local are you using?

```
├─┬ @cmfcmf/docusaurus-search-local@0.10.0
│ └── @docusaurus/core@2.0.0-beta.16 deduped
├── @docusaurus/core@2.0.0-beta.16
└─┬ @docusaurus/preset-classic@2.0.0-beta.16
  ├── @docusaurus/core@2.0.0-beta.16 deduped
  ├─┬ @docusaurus/plugin-content-blog@2.0.0-beta.16
  │ └── @docusaurus/core@2.0.0-beta.16 deduped
  ├─┬ @docusaurus/plugin-content-docs@2.0.0-beta.16
  │ └── @docusaurus/core@2.0.0-beta.16 deduped
  ├─┬ @docusaurus/plugin-content-pages@2.0.0-beta.16
  │ └── @docusaurus/core@2.0.0-beta.16 deduped
  ├─┬ @docusaurus/plugin-debug@2.0.0-beta.16
  │ └── @docusaurus/core@2.0.0-beta.16 deduped
  ├─┬ @docusaurus/plugin-google-analytics@2.0.0-beta.16
  │ └── @docusaurus/core@2.0.0-beta.16 deduped
  ├─┬ @docusaurus/plugin-google-gtag@2.0.0-beta.16
  │ └── @docusaurus/core@2.0.0-beta.16 deduped
  ├─┬ @docusaurus/plugin-sitemap@2.0.0-beta.16
  │ └── @docusaurus/core@2.0.0-beta.16 deduped
  ├─┬ @docusaurus/theme-classic@2.0.0-beta.16
  │ └── @docusaurus/core@2.0.0-beta.16 deduped
  └─┬ @docusaurus/theme-search-algolia@2.0.0-beta.16
    └── @docusaurus/core@2.0.0-beta.16 deduped
```

### Which Node.js version are you using?

v16.3.0

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

### How does your plugin config look like?

```
 plugins: [
    [
      require.resolve("@cmfcmf/docusaurus-search-local"),
      {
        language: "fr",
      }
    ],
  ],
```

### Additional context

wsl on local or gitlab ci failed

```
image: node:15.12-alpine3.13

before_script:
  - node -v
  - cat /etc/*release
  - yarn -v


stages:
  - test
  - deploy

pages:
  stage: deploy
  script:
    - npm install --force
    - npm run build
    - mv ./build ./public
  artifacts:
    paths:
    - public
  # only:
  #   - pages
```
