### ISSUE TITLE
Add a disable highlighting option

### ISSUE THREAD

**Issue by SCsupercraft** [cmfcmf/docusaurus-search-local#223]
It is nice that the **highlighting** goes away when **reloading the page**, but sometimes it would still be nice to have a **config option** to **disable** the **highlighting altogether**.

**Comment by bmaupin** [comment]
Yes, please. I think the highlighting is pretty bad for the reasons already listed in #28

It looks like it's using [mark.js](https://markjs.io/)

I found a workaround; add this to src/css/custom.css:

```css
mark {
  background-color: unset;
  color: unset;
}
```
